version: '3'

services:
mysql-db:
image: mysql:latest
ports:
- "3306:3306"
environment:
- MYSQL_ROOT_PASSWORD=root
- MYSQL_DATABASE=todolist

spring-boot:
build: ./todolist-back
ports:
- "8080:8080"
depends_on:
- mysql-db
environment:
- DATABASE_HOST=mysql-db
- DATABASE_PASSWORD=root
- DATABASE_NAME=todolist